version: '3.8'

services:
  backend:
    build: .
    container_name: scoring_backend
    ports:
      - "8000:8000"
    command: python -m uvicorn service:app --host 0.0.0.0 --port 8000
    volumes:
      - ./model.pkl:/app/model.pkl

  frontend:
    build: .
    container_name: scoring_frontend
    ports:
      - "8501:8501"
    command: streamlit run app.py --server.address=0.0.0.0 --server.port=8501
    depends_on:
      - backend
    volumes:
      - ./model.pkl:/app/model.pkl